listeners=http://34.30.26.43:80

# Use this setting to specify the bootstrap servers for your Kafka cluster and it
# will be used both for selecting the leader schema registry instance and for storing the data for
# registered schemas.
kafkastore.bootstrap.servers=PLAINTEXT://35.226.62.39:9092

# The name of the topic to store schemas in
kafkastore.topic=_schemas_schemaregistry_confluent

# If true, API requests that fail will include extra debugging information, including stack traces
debug=false
